fix undefined reference to 'operator new'
Before this commit, go called `pkg-config --libs libhs` and passed
-lstdc++ -L/usr/local/lib -lhs to `ld`. It didn't work for two reasons:

  * hs depends on stdc++, so it should be before stdc++ in ld options
  * hs depends also on -lm and -lc

`pkg-config --libs libhs --static` returns correct options for ld.